### ISSUE TITLE
damping func parameters

### ISSUE THREAD

**Issue by vuoanh** [MolSSI-SSS/QM_2017_SSS_Team10#31]
damping_func(iteration, damp_value, F_old, F_new):
What is iteration?

**Comment by bgutier5** [comment]
Iteration is the index of the for loop where this functions is executed. Like this code. It is just a number from 1 to 25.

for **iteration** in range(25):
    # F_pq = H_pq + 2 * g_pqrs D_rs - g_prqs D_rs
