### ISSUE TITLE
variable undefined

### ISSUE THREAD

**Issue by vuoanh** [MolSSI-SSS/QM_2017_SSS_Team10#54]
def damping_func(iteration, damp_start, F_old, F_new):
    '''
    This fuction updates the fock matrix by a damping fuction
    '''
    if iteration >= damp_start:
        F = damp_value * F_old + (1.0 - damp_value) * F_new
    else:
        F = F_new
    return F

In this function, you havent defined the variable "damp_value"

**Comment by bgutier5** [comment]
The damp_value is a global variable, so even if its not defined the function will still work. Would you still like me to pass it on to the function?

At the moment all these parameters are global variables.

e_conv = 1.e-6
d_conv = 1.e-6
nel = 5
damp_value = 0.20
damp_start = 5

**Comment by bgutier5** [comment]
At the moment all this parameters are global variables.

e_conv = 1.e-6
d_conv = 1.e-6
nel = 5
damp_value = 0.20
damp_start = 5

**Comment by mtesseracted** [comment]
If the global is not defined in helper2 then the function will be unable to see it when it is tested.  This seems like a parameter that should be passed to me.

**Comment by bgutier5** [comment]
ok, I will pass it on to the function.

**Comment by bgutier5** [comment]
The new pull request contains a fix to this issue.

**Comment by mtesseracted** [comment]
Fixed in PR 61

**Comment by vuoanh** [comment]
Thanks for the detailed document, @bgutier5  
mol is undefine in the function "energy_conv". Can you fix that?

**Comment by bgutier5** [comment]
done
