### ISSUE TITLE
Undefined reference in helper2:energy_conv()

### ISSUE THREAD

**Issue by mtesseracted** [MolSSI-SSS/QM_2017_SSS_Team10#60]
https://github.com/MolSSI-SSS/QM_2017_SSS_Team10/blob/master/qm10/helper2.py#L76

**Comment by mtesseracted** [comment]
undefined reference is mol.nuclear_repulsion_energy()

**Comment by bgutier5** [comment]
Just fixed it

**Comment by mtesseracted** [comment]
fixed in PR 62
