### ISSUE TITLE
helper1 outdated

### ISSUE THREAD

**Issue by mtesseracted** [MolSSI-SSS/QM_2017_SSS_Team10#62]
Since helper2 has been updated helper1 is out of date.  The function gradient_calculation() -> gradient(), damping_function() -> damping_func(), it also changed the number of parameters required.  It now requires a psi4 molecule object.  I know most functions in helper1 take a geometry as input but since they all use that to make a molecule I think we should switch them all to passing the molecule object itself.

**Comment by bgutier5** [comment]
Do you mean that we should pass the "mol" class even though they are not used inside the function? In my case only the function "energy_conv" need the "mol" class.

**Comment by mtesseracted** [comment]
I'm referring to integrals() and hartree_fock() that take a geom argument but they only need it to instantiate a molecule.

**Comment by mtesseracted** [comment]
fixed in merge 66
