### ISSUE TITLE
Update update_D 

### ISSUE THREAD

**Issue by vuoanh** [MolSSI-SSS/QM_2017_SSS_Team10#68]
```
import numpy as np
import psi4

def update_D(diag, F, A, nel):
    eps, C = diag(F, A)
```

Could you change it to:
```
import numpy as np
import psi4
import helper1

def update_D(F, A, nel):
    eps, C = helper1.diag(F, A)
```

**Comment by mtesseracted** [comment]
This is correct as it stands now, it passes a general function, we just happen to want the specific one from helper1, if you want to specify it is now longer a parameter and should be hard-coded.  They're both valid methods.

**Comment by bgutier5** [comment]
I cancelled my pull request earlier so as to not break you code more. So how would you like to proceed @vuoanh ?

**Comment by vuoanh** [comment]
Could you make another pull request? I can fix my code afterwards.
